encoding: UTF-8
title: 钟辰（Leo）
logo: /assets/img/picture.jpg
description: >
  1Email zy21036@nottingham.edu.ch<br>
  电话 +86 18605709999<br>
  <a href="https://www.linkedin.com/in/chen-zhong18">View My LinkedIn Profile</a><br>
  <a href="https://zczss.github.io/zccss.github.io/english">English version</a>
show_downloads: False
theme: jekyll-theme-minimal
