encoding: UTF-8
title: 钟辰（Leo）
logo: /assets/img/picture.jpg
description: >
  Email zy21036@nottingham.edu.ch<br>
  电话 +86 18605709999<br>
  <a href="www.linkedin.com/in/chen-zhong18">View My LinkedIn Profile</a><br>
  <a href="/english.md">English version</a>
show_downloads: False
theme: jekyll-theme-minimal
